version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ../environment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../src:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lumen
      MYSQL_USER: lumenuser
      MYSQL_PASSWORD: lumenpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: