version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: x-nginx
    ports:
      - "8080:8080"
    volumes:
      - ../environment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../src:/app/src
    depends_on:
      - php

  php:
    build:
      context: ../
      dockerfile: Dockerfile
    working_dir: /app/src
    container_name: x-php
    volumes:
      - ../src:/app/src

  mysql:
    image: mysql:8.0
    container_name: x-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lumen
      MYSQL_USER: lumenuser
      MYSQL_PASSWORD: lumenpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: